
export const FoodPage = () => {
  return (
    <div>
      <p>Footer</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
    </div>
  )
}
