
export const FoodPage = () => {
  return (
    <div>
      <h2>Food pages</h2>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <p>Contenido</p>
      <h2>Food pages</h2>
    </div>
  )
}
